### PR TITLE
Refactor to fix warning

### LINKED ISSUE #2: Is there a better way to redefine the `::Trilogy` constant?
When loading the `TrilogyAurora` module, the following warnings appear:

```
> bin/rails console
/Users/aidanlavis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/trilogy_aurora-0.1.0/lib/trilogy_aurora.rb:105: warning: already initialized constant Trilogy
/Users/aidanlavis/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/trilogy-2.5.0/lib/trilogy/version.rb:1: warning: previous definition of Trilogy was here
```

This is clearly caused by this code:

https://github.com/a-lavis/trilogy_aurora/blob/8f7b5de76afb7a60d09aa23d7680ae66902286bd/lib/trilogy_aurora.rb#L104-L105

We are redefining `::Trilogy` to a different class, namely `TrilogyAurora::Trilogy`.

Is there a better way of doing this that doesn't trigger these warnings?

Alternatively, should we be extending the functionality of the `Trilogy` class in a completely different way?

### PR DESCRIPTION
**Pull request by amancevice**
- Simplify testing framework (don't need a whole-assed Docker container)
- Fix up GitHub Action to use new framework
- Instead of monkey patching `::Trilogy` we patch `ActiveRecord::ConnectionAdapters::TrilogyAdapter` to use a version of `::new_client` that creates an instance of `TrilogyAurora::Client` instead of `Trilogy` (fixes #2)
- fix up specs
- bump version

### CODE REVIEW

File: lib/trilogy_aurora.rb [hunk 1]
```diff
@@ -1,111 +1,28 @@
...
-          retry_interval_seconds = [1.5 * (try_count - 1), 10].min
-
-          warn "[trilogy_aurora] Database is readonly. Retry after #{retry_interval_seconds}seconds"
-          sleep retry_interval_seconds
-          reconnect!
-          retry
+require 'trilogy_aurora/version'
+require 'trilogy_aurora/client'
+
+if defined?(ActiveRecord)
```
Comment (a-lavis) [inline lib/trilogy_aurora.rb]: With this change, the gem would only work with `ActiveRecord`, is that right?

If that's the case, should we add it as a dependency to the gemspec?

Comment (amancevice) [reply lib/trilogy_aurora.rb]: we could, I added this to try and avoid that

Comment (amancevice) [reply lib/trilogy_aurora.rb]: the other thing we could do is turn this into a totally new adapter (eg, `trilogy_aurora`)

File: spec/trilogy_aurora_spec.rb [hunk 2]
```diff
@@ -1,263 +1,7 @@
...
-
   it 'has a version number' do
-    expect(TrilogyAurora::VERSION).not_to be_nil
-  end
-
-  describe 'Trilogy' do
-    it 'returns TrilogyAurora::Trilogy' do
-      expect(Trilogy).to eq(TrilogyAurora::Trilogy)
-    end
-  end
```
Comment (a-lavis) [inline spec/trilogy_aurora_spec.rb:24]: The tests for `TrilogyAurora::Client` look great - could we also add some tests ensuring that, when `Trilogy` is used, it refers to our new `TrilogyAurora::Client` class?

File: README.md [hunk 3]
```diff
@@ -14,32 +14,20 @@ Essentially, the [mysql2-aurora](https://github.com/alfa-jpn/mysql2-aurora) gem
...
-Trilogy.new(
-  host:             'localhost',
-  username:         'root',
-  password:         'change_me',
-  aurora_max_retry: 5,
-  aurora_disconnect_on_readonly: true
-)
-```
-
-with Rails >= 7.1, in `database.yml`
```
Comment (a-lavis) [inline README.md]: Now that this PR is taking the ActiveRecord-agnostic strategy, can we leave this part in the readme?

**Review by a-lavis — APPROVED** [review]
awesome, thank you!
